#!/bin/bash
# Push file to sdcard
ARG=$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS

chk=$(echo ${ARG} |wc -w)
if [ ${chk} -ne 1 ]; then
    gdialog --title "Error" --msgbox "Only do one thing at a time, got ${chk}" 200 200
    exit 0
else
    which adb &>/dev/null
    if [ $? -ne 0 ]; then
        gdialog --title "Adb not found" --msgbox "Adb binary is not found, please install adb" 200 200
        exit 1
    fi
    gdialog --title "Finding device" --msgbox "Waiting for you device to become available to push $ARG, if not connected, do so now please." 200 200
    adb wait-for-device
    adb push $ARG /sdcard/
    gdialog --title "Complete" --msgbox "$ARG pushed to sdcard" 200 200
fi
